name = "cozy-behdaung-node-api"
main = "src/index.ts"
compatibility_date = "2024-09-23" # Must be at least this date for v2 compat
compatibility_flags = ["nodejs_compat"]

[build]
watch_dir = "src"

[dev]
port = 3000